INSERT INTO tb_product
(brand, model, description, currency, price, image)
VALUES
    ('Apple',
     'iPhone 15',
     'Smartphone Apple com tela Super Retina XDR, chip A16 Bionic e câmera principal de 48 MP.',
     'USD',
     699.00,
     'https://example.com/images/iphone-15.jpg'),

    ('Apple',
     'iPhone 15 Pro',
     'Smartphone premium Apple com chip A17 Pro, estrutura em titânio e sistema de câmeras profissionais.',
     'USD',
     999.00,
     'https://example.com/images/iphone-15-pro.jpg'),

    ('Apple',
     'iPhone 16',
     'Smartphone Apple com chip A18, câmera Fusion de 48 MP e recursos avançados de inteligência artificial.',
     'USD',
     799.00,
     'https://example.com/images/iphone-16.jpg'),

    ('Samsung',
     'Galaxy S24',
     'Smartphone Samsung com tela Dynamic AMOLED 2X, câmera tripla e recursos Galaxy AI.',
     'USD',
     799.00,
     'https://example.com/images/galaxy-s24.jpg'),

    ('Samsung',
     'Galaxy S24 Ultra',
     'Smartphone premium Samsung com S Pen, câmera de 200 MP, zoom avançado e tela de alta resolução.',
     'USD',
     1299.00,
     'https://example.com/images/galaxy-s24-ultra.jpg'),

    ('Samsung',
     'Galaxy A55',
     'Smartphone intermediário Samsung com tela Super AMOLED, câmera tripla e bateria de longa duração.',
     'USD',
     449.00,
     'https://example.com/images/galaxy-a55.jpg'),

    ('Google',
     'Pixel 8',
     'Smartphone Google com Android puro, câmera com processamento computacional avançado e recursos de IA.',
     'USD',
     699.00,
     'https://example.com/images/pixel-8.jpg'),

    ('Google',
     'Pixel 9',
     'Smartphone Google com tela Actua, chip Tensor G4 e recursos avançados de inteligência artificial.',
     'USD',
     799.00,
     'https://example.com/images/pixel-9.jpg'),

    ('Xiaomi',
     'Redmi Note 13 Pro',
     'Smartphone Xiaomi intermediário com câmera de alta resolução, tela AMOLED e carregamento rápido.',
     'USD',
     349.00,
     'https://example.com/images/redmi-note-13-pro.jpg'),

    ('Xiaomi',
     'Xiaomi 14',
     'Smartphone premium Xiaomi com processador Snapdragon, tela AMOLED e sistema de câmeras Leica.',
     'USD',
     899.00,
     'https://example.com/images/xiaomi-14.jpg'),

    ('Motorola',
     'Moto G Power',
     'Smartphone Motorola focado em autonomia de bateria, tela ampla e bom custo-benefício.',
     'USD',
     249.00,
     'https://example.com/images/moto-g-power.jpg'),

    ('Motorola',
     'Edge 50 Pro',
     'Smartphone Motorola premium com tela pOLED, carregamento rápido e câmeras avançadas.',
     'USD',
     599.00,
     'https://example.com/images/edge-50-pro.jpg'),

    ('OnePlus',
     'OnePlus 12',
     'Smartphone premium com processador Snapdragon, tela AMOLED de alta taxa de atualização e carregamento rápido.',
     'USD',
     799.00,
     'https://example.com/images/oneplus-12.jpg'),

    ('OnePlus',
     'OnePlus Nord CE 4',
     'Smartphone intermediário com tela AMOLED, bateria de grande capacidade e carregamento rápido.',
     'USD',
     299.00,
     'https://example.com/images/oneplus-nord-ce-4.jpg');