spring.application.name=product-api
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost/db_product
spring.datasource.username=postgres
spring.datasource.password=postgres

app.promotion.message=Christmas Promotion

#spring.profiles.active=es

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500

spring.config.import=optional:consul: